### ISSUE TITLE
Map matching does not work

### ISSUE THREAD

**Issue by xafizoff** [hamler-lang/documentation#19]
> m = #{"foo" => "bar", "bar" => "foo"}
> #{"foo" := a, "bar" := b} = m
Unexpected token '#' at line 1, column 1

**Comment by Kleidukos** [comment]
Are you doing this from the REPL or in a source file?

**Comment by emqplus** [comment]
@xafizoff The REPL does not support top level bindings still:(

**Comment by xafizoff** [comment]
Then you should remark this in the docs, I think

**Comment by sdzx-1** [comment]
Support top level bindings Now.
