### ISSUE TITLE
Inconsistencies regarding booleans

### ISSUE THREAD

**Issue by Kleidukos** [hamler-lang/documentation#3]
The Cheatsheet's paragraph on [Tuples](https://github.com/hamler-lang/documentation/blob/master/Cheatsheet.md#tuples) references the following tuple:
```haskell
(1, "a", True)
```
However, it is mentioned earlier that Booleans are lowercased.
The inconsistency can be pretty confusing when one is used to both Haskell's `True` and Erlang's `true`.

Would you like me to submit a PR?

**Comment by Time-Hu** [comment]
Yeah, thanks. It should be in lowercase. And, I should have reviewed all the doc more carefully.

**Comment by Kleidukos** [comment]
A bold choice, but okay. :)
Thanks!
